version: '3'
services:
  db:
    container_name: dataBaseMySql
    restart: always
    image: mysql:8.0.27 # or mysql:8.0.28
    volumes:
        - mysql-db:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: vrum
    ports:
        - "3306:3306"
volumes:
  mysql-db:
    name: dataBase-vol